version: '3.8'
services:
  auth:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./prod-config.yml:/opt/conf/prod-config.yml
    command:
      - "-conf=/opt/conf/prod-config.yml"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local