rest-server-config:
  port: 8080
  host: 0.0.0.0

tenant-config:
  - tenant-name: normal
    db-driver: pgx
    host: db
    port: 5432
    username: postgres
    password: postgres
    jwt-key: ppLXwPy58S1lz1pVqXLR4yDgoKTowqXV
    jwt-expired-time: 8