// Code generated by protoc-gen-go-grpc_server. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc_server v1.2.0
// - protoc             v5.26.1
// source: api/grpc_server/proto/validate.proto

package domain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc_server package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ValidateClient is the client API for Validate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidateClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type validateClient struct {
	cc grpc.ClientConnInterface
}

func NewValidateClient(cc grpc.ClientConnInterface) ValidateClient {
	return &validateClient{cc}
}

func (c *validateClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/Validate/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidateServer is the server API for Validate service.
// All implementations must embed UnimplementedValidateServer
// for forward compatibility
type ValidateServer interface {
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedValidateServer()
}

// UnimplementedValidateServer must be embedded to have forward compatible implementations.
type UnimplementedValidateServer struct {
}

func (UnimplementedValidateServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedValidateServer) mustEmbedUnimplementedValidateServer() {}

// UnsafeValidateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidateServer will
// result in compilation errors.
type UnsafeValidateServer interface {
	mustEmbedUnimplementedValidateServer()
}

func RegisterValidateServer(s grpc.ServiceRegistrar, srv ValidateServer) {
	s.RegisterService(&Validate_ServiceDesc, srv)
}

func _Validate_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Validate/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Validate_ServiceDesc is the grpc.ServiceDesc for Validate service.
// It's only intended for direct use with grpc_server.RegisterService,
// and not to be introspected or modified (even as a copy)
var Validate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Validate",
	HandlerType: (*ValidateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _Validate_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc_server/proto/validate.proto",
}
